// let 동물 : string | number | undefined;
let 동물;
let 닝겐 = { name: 'kim', age: 22 };
console.log("닝겐", 닝겐);
const 이름 = { first: 'kim' };
console.log("이름.", 이름.first);
이름.first = 'park';
console.log("이름.", 이름.first);
const 여친 = { name: '수지' };
let 좌표 = { x: 1, y: 2 };
